# Docker compose
version: '3.7'

services:

  # Frontend service

  # Backend service
  backend:
    image: backend_image
    build:
      context: ./app-back/
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app-back:/app-back

  # Database service
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: